/* FIVE app.js — rebuilt admin loaders with defensive error handling.
 * Uses the existing Supabase schema/RPCs and existing index.html IDs.
 */
const supabaseClient = window.supabase.createClient(
  window.FIVE_SUPABASE_URL,
  window.FIVE_SUPABASE_KEY,
  { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }
);
const $ = id => document.getElementById(id);
const views = ["home","auth","play","result","calls","eye","daily","rankings","submit","admin"];
let currentSession=null, authMode="signin", currentRound=null, myCalls=[], busy=false, callsLoading=false, isFiveAdmin=false, adminBusy=false;
let adminArtistRows=[], adminSubmissionRows=[], adminSubmissionPage=1, adminSubmissionTotal=0, adminArtistPage=1, adminArtistTotal=0, rankingPage=1;
const ADMIN_PAGE_SIZE=20, RANKING_PAGE_SIZE=30;
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function url(v){const s=String(v||"").trim();return s?(/^https?:\/\//i.test(s)?s:"https://"+s):"";}
function normalizeInstagram(v){const raw=String(v||"").trim();if(!raw)return"";const u=raw.replace(/^@/,"");if(/^[A-Za-z0-9._]{1,30}$/.test(u)&&!/instagram\.com/i.test(u))return`https://www.instagram.com/${u}/`;try{const p=new URL(url(raw));if(!/(^|\.)instagram\.com$/i.test(p.hostname))return"";return`https://www.instagram.com/${p.pathname.replace(/^\/+|\/+$/g,"")}/`;}catch(_){return"";}}
function show(id, syncUrl=true){views.forEach(v=>$(v)?.classList.add("hidden"));$(id)?.classList.remove("hidden");if(syncUrl&&views.includes(id)){const next="#"+id;if(location.hash!==next)history.pushState({fiveView:id},"",next);}} 
function routeFromUrl(){const raw=(location.hash||"").replace(/^#\/?/,"").split(/[?&]/)[0].toLowerCase();const route=views.includes(raw)?raw:"home";if(route==="admin"){void openAdmin();return;}if(route==="play"){if(!signedIn()){authView("Sign in to make a call.");return;}show("play",false);void newRound();return;}if(route==="eye"){if(!signedIn()){authView("Sign in to build YOUR EYE.");return;}show("eye",false);renderEye();return;}if(route==="calls"){viewCalls();return;}if(route==="submit"){submitArtist();return;}if(route==="rankings"){show("rankings",false);void rankingsLoadOnly();return;}if(route==="auth"){authView();return;}if(route==="daily"){daily();return;}if(route==="result"){show(signedIn()?"play":"home",false);if(signedIn())void newRound();return;}homeFromRoute();}
function homeFromRoute(){show("home",false);updateAuthUI();void loadHomeData();}
async function rankingsLoadOnly(){if($("rankList"))$("rankList").innerHTML='<div class="small">Loading ranking…</div>';try{const{data,error}=await withTimeout(supabaseClient.rpc("get_public_rankings"),12000,"Ranking");if(error)throw error;const rows=Array.isArray(data)?data:[];if($("rankingLabel"))$("rankingLabel").textContent=rows.length+" ARTISTS";if($("rankList"))$("rankList").innerHTML=rows.length?rows.slice((rankingPage-1)*RANKING_PAGE_SIZE,rankingPage*RANKING_PAGE_SIZE).map((r,i)=>`<div class="rank-row"><div class="rank-num">#${escapeHtml(r.rank??((rankingPage-1)*RANKING_PAGE_SIZE+i+1))}</div><div><div class="rank-artist">${escapeHtml(r.name||"Artist")}</div><div class="rank-country">${escapeHtml(r.country||"Country not listed")}</div></div><div class="rank-choice">${Number(r.choices||0)} CHOICES</div></div>`).join(""):'<div class="small">No public ranking data yet.</div>';}catch(e){message("rankingMessage",e.message||"Ranking unavailable.","error");if($("rankList"))$("rankList").innerHTML="";}}
window.addEventListener("popstate",()=>routeFromUrl());
function message(id,text,type=""){const e=$(id);if(!e)return;e.textContent=String(text||"");e.className="message"+(type?" "+type:"");e.classList.toggle("hidden",!text);}
function signedIn(){return!!currentSession?.user;}
function setButton(id,disabled,text){const b=$(id);if(!b)return;if(!b.dataset.original)b.dataset.original=b.textContent;b.disabled=disabled;b.textContent=disabled?text:b.dataset.original;}
function fiveVisitorId(){try{let id=localStorage.getItem("five_visitor_id");if(!id){id=crypto.randomUUID?crypto.randomUUID():"v-"+Date.now()+Math.random().toString(36).slice(2);localStorage.setItem("five_visitor_id",id);}return id;}catch(_){return"v-"+Date.now()+Math.random().toString(36).slice(2);}}
function trackEvent(type){try{void supabaseClient.rpc("five_track_event",{p_event_type:type,p_visitor_id:fiveVisitorId(),p_path:location.pathname}).then(({error})=>{if(error)console.warn("FIVE analytics failed",error.message);});}catch(_){}}
function playCallCount(calls=myCalls){return calls.filter(c=>(c.mode||"play")==="play").length;}
function updateAuthUI(){const ok=signedIn();if($("authNav"))$("authNav").textContent=ok?"ACCOUNT":"SIGN IN";if($("counter"))$("counter").textContent=ok?(currentSession.user.email||"SIGNED IN"):"SIGNED OUT";if($("homeCalls"))$("homeCalls").textContent=ok?String(playCallCount()):"Sign in";if($("signOutButton"))$("signOutButton").classList.toggle("hidden",!ok);if($("authPassword"))$("authPassword").disabled=ok;if($("authSubmit"))$("authSubmit").disabled=ok;}
function authView(text=""){show("auth");updateAuthUI();message("authMessage",text);}
function setAuthMode(mode){authMode=mode;const signup=mode==="signup";if($("authTitle"))$("authTitle").textContent=signup?"CREATE ACCOUNT":"SIGN IN";if($("authCopy"))$("authCopy").textContent=signup?"Create an account to start building your record.":"Sign in to make calls, submit artists, and build your record.";if($("authSubmit"))$("authSubmit").textContent=signup?"CREATE ACCOUNT":"SIGN IN";$("authPassword")&&($("authPassword").disabled=false);$("authPasswordConfirmField")?.classList.toggle("hidden",!signup);$("authModeSwitch")&&($("authModeSwitch").textContent=signup?"SIGN IN":"CREATE ACCOUNT");message("authMessage","");}
function toggleAuthMode(){setAuthMode(authMode==="signup"?"signin":"signup");}
async function submitAuth(){const email=$("authEmail")?.value.trim(),password=$("authPassword")?.value;if(!email||!password)return message("authMessage","Enter an email and password.","error");if(authMode==="signup"&&password!==$("authPasswordConfirm")?.value)return message("authMessage","Passwords do not match.","error");setButton("authSubmit",true,authMode==="signup"?"CREATING...":"SIGNING IN...");try{const r=authMode==="signup"?await supabaseClient.auth.signUp({email,password}):await supabaseClient.auth.signInWithPassword({email,password});if(r.error)throw r.error;currentSession=r.data.session||currentSession;if(authMode==="signup"&&!currentSession)return message("authMessage","Account created. Check your email to confirm your address, then sign in.","success");trackEvent(authMode==="signup"?"account_signup":"account_login");await loadMyCalls();updateAuthUI();home();}catch(e){message("authMessage",e.message||"Authentication failed.","error");}finally{setButton("authSubmit",false);}}
async function signOut(){const{error}=await supabaseClient.auth.signOut();if(error)return message("authMessage",error.message,"error");currentSession=null;myCalls=[];currentRound=null;home();}
function home(){show("home");updateAuthUI();void loadHomeData();}
async function withTimeout(promise,ms=12000,label="Request"){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(label+" timed out after "+Math.round(ms/1000)+" seconds.")),ms);})]);}finally{clearTimeout(timer);}}
async function loadHomeData(){const list=$("homeTopFive"),artists=$("globalArtists"),choices=$("globalChoices");if(list)list.innerHTML='<div class="small">Loading live ranking…</div>';const stats=withTimeout(supabaseClient.rpc("get_public_stats"),12000,"Global statistics").then(({data,error})=>{if(error)throw error;const s=Array.isArray(data)?data[0]:data;if(artists)artists.textContent=String(s?.approved_artists??"—");if(choices)choices.textContent=String(s?.total_choices??"—");}).catch(e=>{if(artists)artists.textContent="—";if(choices)choices.textContent="—";console.warn("FIVE stats:",e);});try{const{data,error}=await withTimeout(supabaseClient.rpc("get_public_rankings"),12000,"Public ranking");if(error)throw error;if(list){const rows=Array.isArray(data)?data:[];list.innerHTML=rows.length?rows.slice(0,5).map((r,i)=>`<div class="home-rank-row"><div class="home-rank-num">#${escapeHtml(r.rank??i+1)}</div><div><div class="home-rank-name">${escapeHtml(r.name||"Artist")}</div><div class="home-rank-country">${escapeHtml(r.country||"Country not listed")}</div></div><div class="home-rank-choices">${Number(r.choices||0)} choices</div></div>`).join(""):'<div class="small">No public calls recorded yet.</div>';}}catch(e){if(list)list.innerHTML='<div class="small">Ranking unavailable. '+escapeHtml(e.message||"Please refresh.")+'</div>';}await stats;}
async function submitAuthCompat(){return submitAuth();}
function normalizeRound(data){const rows=Array.isArray(data)?data:(data?.artists||data?.items||data?.round_artists||[]);const id=data?.round_id||data?.id||rows[0]?.round_id||null;return{roundId:id,artists:rows.map(r=>({id:r.artist_id||r.id,name:r.name||"Untitled artist",country:r.country||"",instagramUrl:r.instagram_url||"",roundId:r.round_id||id})).filter(a=>a.id)};}
async function play(){if(!signedIn())return authView("Sign in to make a call.");trackEvent("play_round");show("play");await newRound();}
async function newRound(){if(busy)return;busy=true;if($("grid"))$("grid").innerHTML="";if($("roundLabel"))$("roundLabel").textContent="LOADING";message("playMessage","Loading five artists...");try{const{data,error}=await withTimeout(supabaseClient.rpc("create_play_round",{p_mode:"play"}),15000,"Artist round");if(error)throw error;currentRound=normalizeRound(data);if(!currentRound.roundId||currentRound.artists.length!==5)throw new Error("The server did not return exactly five artists.");if($("roundLabel"))$("roundLabel").textContent="SERVER ROUND";message("playMessage","");renderRound();}catch(e){if($("roundLabel"))$("roundLabel").textContent="ERROR";message("playMessage",e.message||"Could not load artists.","error");}finally{busy=false;}}
function renderRound(){if(!$("grid"))return;$("grid").innerHTML=currentRound.artists.map((a,i)=>`<article class="card"><div class="number">0${i+1}</div><div class="card-content"><div class="name">${escapeHtml(a.name)}</div><div class="country">${escapeHtml(a.country||"Country not listed")}</div></div><div class="card-actions">${a.instagramUrl?`<a class="instagram" href="${escapeHtml(url(a.instagramUrl))}" target="_blank" rel="noopener">INSTAGRAM</a>`:'<span class="instagram instagram-disabled">INSTAGRAM</span>'}<button class="choose" onclick="choose(${i})">CHOOSE</button></div></article>`).join("");}
async function choose(i){const a=currentRound?.artists[i];if(!a||busy)return;busy=true;document.querySelectorAll(".choose").forEach(b=>b.disabled=true);message("playMessage","Recording your call...");try{const{error}=await withTimeout(supabaseClient.rpc("record_call",{p_round_id:currentRound.roundId,p_artist_id:a.id,p_rank_at_choice:null}),15000,"Saving choice");if(error)throw error;const n=playCallCount()+1;if($("chosen"))$("chosen").textContent=a.name;if($("chosenMeta"))$("chosenMeta").textContent=a.country||"Country not listed";if($("resultCount"))$("resultCount").textContent=String(n);const milestones=[10,25,50,100,250,500,1000,3000,5000],titles=["YOUR EYE","EXPLORER SIGNAL","TASTE PROFILE","FIVE INSIDER","COLLECTOR LEVEL","FIVE ICON","TASTE AUTHORITY","CULTURE SHAPER","FIVE LEGEND"],idx=milestones.findIndex(x=>n<x),target=milestones[idx<0?milestones.length-1:idx],title=titles[idx<0?titles.length-1:idx],remaining=Math.max(0,target-n);if($("nextCheck"))$("nextCheck").textContent=idx<0?"ALL CURRENT LEVELS UNLOCKED":`${remaining} CALLS → ${title}`;if($("resultProgress"))$("resultProgress").style.width=(idx<0?100:Math.max(0,n/target*100))+"%";if($("progressCaption"))$("progressCaption").textContent=idx<0?"All current milestones reached.":`${remaining} more calls to unlock ${title}`;message("playMessage","");show("result");window.dispatchEvent(new CustomEvent("five:call-recorded"));void loadMyCalls();updateAuthUI();}catch(e){message("playMessage",e.message||"Could not save this choice.","error");}finally{busy=false;document.querySelectorAll(".choose").forEach(b=>b.disabled=false);}}
function nextRound(){play();}
async function loadMyCalls(){if(!signedIn()||callsLoading){if(!signedIn())myCalls=[];return;}callsLoading=true;try{const{data,error}=await withTimeout(supabaseClient.from("calls").select("id,created_at,rank_at_choice,artist_id,mode,artists(id,name,country,instagram_url,website_url)").eq("user_id",currentSession.user.id).order("created_at",{ascending:false}).limit(2000),15000,"Call history");if(error)throw error;myCalls=data||[];updateAuthUI();}catch(e){console.warn("FIVE call history:",e);message("callsMessage","Could not load your call history: "+e.message,"error");}finally{callsLoading=false;}}
function viewCalls(){if(!signedIn())return authView("Sign in to see your calls.");show("calls");renderCalls();}
function renderCalls(){if(!$("callsList"))return;if($("activeLabel"))$("activeLabel").textContent=`${myCalls.length} CALL${myCalls.length===1?"":"S"}`;if(!myCalls.length){$("callsList").innerHTML='<div class="report"><h3>No calls yet.</h3><div class="small">Make your first call to start building a real history.</div></div>';return;}$("callsList").innerHTML=myCalls.map(c=>{const a=c.artists||{};return`<div class="call-card"><div class="rank-old">—</div><div><div class="call-name">${escapeHtml(a.name||"Artist")}</div><div class="call-country">${escapeHtml(a.country||"Country not listed")} · ${escapeHtml(c.created_at?new Date(c.created_at).toLocaleDateString():"")}</div></div><div class="rank-now developing">RECORDED</div></div>`;}).join("");}
function eye(){if(!signedIn())return authView("Sign in to build YOUR EYE.");show("eye");renderEye();}
function renderEye(){const n=playCallCount();if($("eyeCount"))$("eyeCount").textContent=`${n} REAL CALL${n===1?"":"S"}`;if($("eyeHeadline"))$("eyeHeadline").textContent=n<10?"Your eye is starting to form.":"Your history is now measurable.";if($("eyeCopy"))$("eyeCopy").textContent=n<10?`Make ${10-n} more calls to unlock the first real signal.`:"Your actual choices are recorded.";const ms=[10,25,50,100,250,500,1000,3000,5000],names=["YOUR EYE","EXPLORER SIGNAL","TASTE PROFILE","FIVE INSIDER","COLLECTOR LEVEL","FIVE ICON","TASTE AUTHORITY","CULTURE SHAPER","FIVE LEGEND"],i=ms.findIndex(x=>n<x),idx=i<0?ms.length-1:i;if($("eyeLevelTitle"))$("eyeLevelTitle").textContent=n>=10?names[Math.max(0,idx-1)]:"FIRST CALL";if($("eyeLevelCopy"))$("eyeLevelCopy").textContent=i<0?"All current milestones reached.":`${ms[idx]-n} more calls to unlock ${names[idx]}.`;if($("eyeLevelProgress"))$("eyeLevelProgress").style.width=Math.min(100,n/ms[idx]*100)+"%";if($("metrics"))$("metrics").innerHTML=[["RECORDED CALLS",n,"Actual choices in your account."],["UNIQUE ARTISTS",new Set(myCalls.map(c=>c.artist_id).filter(Boolean)).size,"Different artists you have chosen."],["HISTORY","LIVE","Based on recorded calls only."]].map(x=>`<div class="metric"><div class="metric-name">${x[0]}</div><div class="metric-num">${escapeHtml(x[1])}</div><div class="metric-copy">${escapeHtml(x[2])}</div></div>`).join("");const counts={};myCalls.forEach(c=>{const a=c.artists||{};if(c.artist_id)counts[c.artist_id]??={name:a.name||"Artist",count:0};if(c.artist_id)counts[c.artist_id].count++;});const fav=Object.values(counts).sort((a,b)=>b.count-a.count).slice(0,5);if($("fiveList"))$("fiveList").innerHTML=fav.length?fav.map(a=>`<div class="five-item"><strong>${escapeHtml(a.name)}</strong><span>${a.count} calls</span></div>`).join(""):'<div class="small">Make calls to build this list.</div>';if($("bestCall"))$("bestCall").textContent=fav[0]?.name||"—";if($("bestCallCopy"))$("bestCallCopy").textContent=fav[0]?`${fav[0].count} recorded calls.`:"Make more calls to build your history.";}
function daily(){if(!signedIn())return authView("Sign in to continue.");show("daily");}
async function rankings(){show("rankings");await rankingsLoadOnly();}
function filterRankings(){rankingPage=1;rankings();}
function submitArtist(){if(!signedIn())return authView("Sign in to submit an artist.");show("submit");}
async function sendSubmission(){if(!signedIn())return authView("Sign in to submit an artist.");const name=$("submissionName")?.value.trim(),country=$("submissionCountry")?.value.trim(),instagram=normalizeInstagram($("submissionInstagram")?.value),website=url($("submissionWebsite")?.value);if(!name||!country||!instagram)return message("submitMessage","Artist name, country, and Instagram are required.","error");try{const{error}=await supabaseClient.rpc("submit_artist",{p_name:name,p_country:country,p_instagram_url:instagram,p_website_url:website||null});if(error)throw error;message("submitMessage","Submission received. FIVE will review it.","success");["submissionName","submissionCountry","submissionInstagram","submissionWebsite"].forEach(id=>{if($(id))$(id).value="";});}catch(e){message("submitMessage",e.message||"Could not submit artist.","error");}}
function shareEye(){const n=playCallCount(),title=$("bestCall")?.textContent||"MY FIVE";const text=`${title} — ${n} real calls on FIVE. Discover. Choose. Rank.`;if(navigator.share)navigator.share({title:"My FIVE Story",text}).catch(()=>{});else alert(text);}
function renderAdminPagination(id,page,total,callback){const el=$(id);if(!el)return;const pages=Math.max(1,Math.ceil(total/ADMIN_PAGE_SIZE)),first=total?(page-1)*ADMIN_PAGE_SIZE+1:0,last=Math.min(page*ADMIN_PAGE_SIZE,total);el.innerHTML=`<div style="display:flex;flex-wrap:wrap;gap:12px;align-items:center;justify-content:space-between;padding-top:16px"><span class="small">Showing ${first}–${last} of ${total}</span><div style="display:flex;align-items:center;gap:10px"><button class="secondary" ${page<=1?"disabled":""} onclick="${callback}(-1)">PREVIOUS</button><span class="small">PAGE ${page} / ${pages}</span><button class="secondary" ${page>=pages?"disabled":""} onclick="${callback}(1)">NEXT</button></div></div>`;}
async function rpcSafe(name,args,timeout=12000){const result=await withTimeout(supabaseClient.rpc(name,args),timeout,name);if(result.error)throw result.error;return result.data;}
function ensureAdminUI(){if(!$("admin")){const main=document.querySelector("main");if(!main)return;const section=document.createElement("section");section.id="admin";section.className="view hidden";section.innerHTML=`<div class="section-head"><div><div class="eyebrow">FIVE CONTROL</div><div class="section-title">ADMIN</div></div><div class="round" id="adminSummary">LOADING</div></div><div id="adminMessage" class="message hidden"></div><div class="report"><div class="eyebrow">ADD ARTIST</div><div class="form"><div class="field"><label>Artist name</label><input id="adminArtistName" required></div><div class="field"><label>Country</label><input id="adminArtistCountry" required></div><div class="field"><label>Instagram</label><input id="adminArtistInstagram" required></div></div><button class="primary" id="adminAddButton" onclick="adminAddArtist()">ADD ARTIST</button></div><div class="report"><div class="section-head"><h3>SUBMISSIONS</h3><button class="secondary" onclick="loadAdminData()">REFRESH</button></div><input id="adminSubmissionSearch" placeholder="Search name or email" oninput="searchAdminSubmissions()"><select id="adminSubmissionStatus" onchange="changeSubmissionStatus()"><option value="pending">PENDING REVIEW</option><option value="approved">APPROVED</option><option value="rejected">REJECTED</option><option value="all">ALL SUBMISSIONS</option></select><div id="adminSubmissions">Loading submissions…</div><div id="adminSubmissionPagination"></div></div><div class="report"><div class="section-head"><h3>ARTISTS</h3></div><input id="adminArtistSearch" placeholder="Search artists" oninput="searchAdminArtists()"><select id="adminArtistStatus" onchange="changeArtistStatus()"><option value="approved">APPROVED</option><option value="pending">PENDING</option><option value="rejected">REJECTED</option><option value="all">ALL ARTISTS</option></select><div id="adminArtists">Loading artists…</div><div id="adminArtistPagination"></div></div><div class="report"><div class="section-head"><h3>STATISTICS</h3><button class="secondary" onclick="loadAdminStats()">REFRESH</button></div><div id="adminStats">Loading statistics…</div></div>`;main.appendChild(section);}let b=$("adminNav");if(!b){const nav=document.querySelector(".topnav");if(nav){b=document.createElement("button");b.id="adminNav";b.textContent="ADMIN";b.onclick=openAdmin;nav.appendChild(b);}}if(b)b.classList.toggle("hidden",!isFiveAdmin);}
async function refreshAdminAccess(){if(!signedIn()){isFiveAdmin=false;$("adminNav")?.classList.add("hidden");if($("admin")&&!$("admin").classList.contains("hidden"))home();return false;}try{isFiveAdmin=(await rpcSafe("is_five_admin"))===true;}catch(e){isFiveAdmin=false;console.error("FIVE admin access check failed:",e);}ensureAdminUI();return isFiveAdmin;}
async function openAdmin(){const ok=await refreshAdminAccess();if(!ok)return authView("Admin access is restricted.");show("admin");await loadAdminData();}
function adminNotice(text,type=""){message("adminMessage",text,type);}
async function loadAdminData(){if(!isFiveAdmin)return adminNotice("Admin access is required.","error");adminNotice("");await Promise.allSettled([loadAdminSubmissions(),loadAdminArtists(),loadAdminStats()]);}
async function loadAdminSubmissions(){const el=$("adminSubmissions");if(!el||!isFiveAdmin)return;el.innerHTML='<div class="small">Loading submissions…</div>';try{const data=await rpcSafe("admin_list_submissions_page",{p_page:adminSubmissionPage,p_page_size:ADMIN_PAGE_SIZE,p_status:$("adminSubmissionStatus")?.value||"pending",p_search:$("adminSubmissionSearch")?.value||""});const rows=Array.isArray(data?.rows)?data.rows:[];adminSubmissionRows=rows;adminSubmissionTotal=Number(data?.total_count||0);if($("adminSummary"))$("adminSummary").textContent=adminSubmissionTotal+" "+($("adminSubmissionStatus")?.value||"pending").toUpperCase();el.innerHTML=rows.length?rows.map(r=>`<div class="panel-row"><div style="flex:1;min-width:0"><strong>${escapeHtml(r.name)}</strong><div class="small">${escapeHtml(r.country)} · ${escapeHtml(r.status)}</div><div class="small">Email: ${escapeHtml(r.email||"Not provided")}</div>${r.status!=="pending"?`<div class="small">Notification: ${escapeHtml(r.notification_status||"not_sent")}${r.notification_error?" · "+escapeHtml(r.notification_error):""}</div>`:""}${r.instagram_url?`<a href="${escapeHtml(normalizeInstagram(r.instagram_url)||"#")}" target="_blank" rel="noopener">OPEN INSTAGRAM</a>`:""}</div>${r.status==="pending"?`<div><button class="primary" onclick="adminReviewSubmission('${escapeHtml(r.id)}','approved')">APPROVE</button><button class="secondary" onclick="adminReviewSubmission('${escapeHtml(r.id)}','rejected')">REJECT</button></div>`:""}</div>`).join(""):'<div class="small">No submissions found for this filter.</div>';renderAdminPagination("adminSubmissionPagination",adminSubmissionPage,adminSubmissionTotal,"changeSubmissionPage");}catch(e){el.innerHTML='<div class="small">Could not load submissions: '+escapeHtml(e.message||e)+'</div>';}}
async function loadAdminArtists(){const el=$("adminArtists");if(!el||!isFiveAdmin)return;el.innerHTML='<div class="small">Loading artists…</div>';try{const data=await rpcSafe("admin_list_artists_page",{p_page:adminArtistPage,p_page_size:ADMIN_PAGE_SIZE,p_status:$("adminArtistStatus")?.value||"approved",p_search:$("adminArtistSearch")?.value||""});adminArtistRows=Array.isArray(data?.rows)?data.rows:[];adminArtistTotal=Number(data?.total_count||0);el.innerHTML=adminArtistRows.length?adminArtistRows.map(r=>`<div class="panel-row"><div style="flex:1"><strong>${escapeHtml(r.name)}</strong><div class="small">${escapeHtml(r.country)} · ${escapeHtml(r.status)}</div>${r.instagram_url?`<a href="${escapeHtml(normalizeInstagram(r.instagram_url)||"#")}" target="_blank" rel="noopener">OPEN INSTAGRAM</a>`:""}</div><div><button class="secondary" onclick="adminEditArtist('${escapeHtml(r.id)}')">EDIT</button><button class="secondary" onclick="adminDeleteArtist('${escapeHtml(r.id)}')">REMOVE</button></div></div>`).join(""):'<div class="small">No artists match this filter.</div>';renderAdminPagination("adminArtistPagination",adminArtistPage,adminArtistTotal,"changeArtistPage");}catch(e){el.innerHTML='<div class="small">Could not load artists: '+escapeHtml(e.message||e)+'</div>';}}
async function loadAdminStats(){const el=$("adminStats");if(!el||!isFiveAdmin)return;el.innerHTML='<div class="small">Loading statistics…</div>';try{const rows=await rpcSafe("admin_get_stats");el.innerHTML=Array.isArray(rows)&&rows.length?'<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:10px">'+rows.map(r=>`<div style="border:1px solid var(--line);padding:14px"><div class="small">${escapeHtml(r.metric)}</div><div style="font-size:25px;font-weight:700;margin-top:8px">${escapeHtml(Number(r.value||0).toLocaleString())}</div></div>`).join("")+'</div>':'<div class="small">No statistics available yet.</div>';}catch(e){el.innerHTML='<div class="small">Could not load statistics: '+escapeHtml(e.message||e)+'</div>';}}
function searchAdminSubmissions(){adminSubmissionPage=1;loadAdminSubmissions();}function changeSubmissionStatus(){adminSubmissionPage=1;loadAdminSubmissions();}function changeSubmissionPage(d){adminSubmissionPage=Math.max(1,adminSubmissionPage+d);loadAdminSubmissions();}function searchAdminArtists(){adminArtistPage=1;loadAdminArtists();}function changeArtistStatus(){adminArtistPage=1;loadAdminArtists();}function changeArtistPage(d){adminArtistPage=Math.max(1,adminArtistPage+d);loadAdminArtists();}function filterAdminArtists(){loadAdminArtists();}
async function adminReviewSubmission(id,decision){if(!isFiveAdmin||adminBusy||!["approved","rejected"].includes(decision))return;if(!confirm(decision==="approved"?"Approve this artist and add them to the public pool?":"Reject this submission?"))return;adminBusy=true;try{await rpcSafe("admin_review_submission",{p_submission_id:id,p_decision:decision});let notice="Decision saved.";try{const d=await supabaseClient.functions.invoke("five-send-review-email",{body:{submission_id:id}});if(d.error)notice+=" Email notification failed: "+d.error.message;else if(d.data?.status==="sent")notice+=" Notification email sent.";else notice+=" Email status: "+(d.data?.status||"unknown");}catch(e){notice+=" Email notification failed: "+e.message;}adminNotice(notice,"success");await loadAdminData();await loadHomeData();}catch(e){adminNotice(e.message||"Could not update submission.","error");}finally{adminBusy=false;}}
async function adminAddArtist(){if(!isFiveAdmin||adminBusy)return;const name=$("adminArtistName")?.value.trim(),country=$("adminArtistCountry")?.value.trim(),instagram=normalizeInstagram($("adminArtistInstagram")?.value);if(!name||!country||!instagram)return adminNotice("Artist name, country, and Instagram are required.","error");adminBusy=true;try{await rpcSafe("admin_add_artist",{p_name:name,p_country:country,p_instagram_url:instagram,p_website_url:null,p_image_url:null,p_categories:[]});["adminArtistName","adminArtistCountry","adminArtistInstagram"].forEach(id=>{if($(id))$(id).value="";});adminNotice("Artist added and approved.","success");await loadAdminData();await loadHomeData();}catch(e){adminNotice(e.message||"Could not add artist.","error");}finally{adminBusy=false;}}
async function adminEditArtist(id){if(!isFiveAdmin||adminBusy)return;const r=adminArtistRows.find(x=>x.id===id);if(!r)return;const name=prompt("Artist name",r.name);if(name===null)return;const country=prompt("Country",r.country);if(country===null)return;const instagram=normalizeInstagram(prompt("Instagram username or URL",r.instagram_url||""));if(!name.trim()||!country.trim()||!instagram)return adminNotice("Enter a valid name, country, and Instagram.","error");adminBusy=true;try{await rpcSafe("admin_update_artist",{p_artist_id:id,p_name:name.trim(),p_country:country.trim(),p_instagram_url:instagram});adminNotice("Artist information updated.","success");await loadAdminData();await loadHomeData();}catch(e){adminNotice(e.message||"Could not update artist.","error");}finally{adminBusy=false;}}
async function adminDeleteArtist(id){if(!isFiveAdmin||adminBusy||!confirm("Remove this artist from the active artist database? Existing call history will be preserved."))return;adminBusy=true;try{const d=await rpcSafe("admin_remove_artist",{p_artist_id:id});adminNotice(d==="archived"?"Artist removed from the active pool. Historical votes were preserved.":"Artist removed from the database.","success");await loadAdminData();await loadHomeData();}catch(e){adminNotice(e.message||"Could not remove artist.","error");}finally{adminBusy=false;}}
async function fiveForgotPassword(){const email=$("authEmail")?.value.trim();if(!email)return message("authMessage","Enter your email first.","error");try{const{error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;message("authMessage","Password reset email sent if this address has an account.","success");}catch(e){message("authMessage",e.message||"Could not send reset email.","error");}}
async function init(){if(!window.FIVE_SUPABASE_URL||!window.FIVE_SUPABASE_KEY)return authView("Supabase configuration is missing.");try{const{data,error}=await supabaseClient.auth.getSession();if(error)throw error;currentSession=data.session;supabaseClient.auth.onAuthStateChange((_event,session)=>{currentSession=session;void loadMyCalls();void refreshAdminAccess();updateAuthUI();});await loadMyCalls();updateAuthUI();await refreshAdminAccess();trackEvent("page_view");routeFromUrl();}catch(e){console.error("FIVE initialization failed",e);authView("Could not initialize FIVE: "+(e.message||"Please refresh."));}}
Object.assign(window,{home,play,eye,daily,rankings,filterRankings,submitArtist,authView,setAuthMode,toggleAuthMode,submitAuth,signOut,nextRound,viewCalls,choose,sendSubmission,shareEye,openAdmin,loadAdminData,adminReviewSubmission,adminAddArtist,adminDeleteArtist,adminEditArtist,filterAdminArtists,searchAdminSubmissions,changeSubmissionStatus,changeSubmissionPage,searchAdminArtists,changeArtistStatus,changeArtistPage,loadAdminStats,fiveForgotPassword});
init();
